PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^TermInfo/', include('apps.TermInfo.urls', namespace='TermInfo')),  # 学期信息模块
    url(r'^ClassInfo/', include('apps.ClassInfo.urls', namespace='ClassInfo')),  # 班级信息模块
    url(r'^Student/', include('apps.Student.urls', namespace='Student')),  # 学生信息模块
    url(r'^Course/', include('apps.Course.urls', namespace='Course')),  # 课程信息模块
    url(r'^ScoreInfo/', include('apps.ScoreInfo.urls', namespace='ScoreInfo')),  # 成绩信息模块
    url(r'^Attendance/', include('apps.Attendance.urls', namespace='Attendance')),  # 学生点名模块
    url(r'^TimeInfo/', include('apps.TimeInfo.urls', namespace='TimeInfo')),  # 学时信息模块
    url(r'^AttendanceState/', include('apps.AttendanceState.urls', namespace='AttendanceState')),  # 出勤状态模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/Course/urls.py
from apps.Course.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'Course'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<courseNo>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<courseNo>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<courseNo>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<courseNo>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/Course/models.py
from django.db import models


class Course(models.Model):
    courseNo = models.CharField(max_length=20, default='', primary_key=True, verbose_name='课程编号')
    courseName = models.CharField(max_length=20, default='', verbose_name='课程名称')
    teacherName = models.CharField(max_length=20, default='', verbose_name='任课教师')
    courseCount = models.IntegerField(default=0,verbose_name='总课时')
    courseScore = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='总学分')

    class Meta:
        db_table = 't_Course'
        verbose_name = '课程信息信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        course = {
            'courseNo': self.courseNo,
            'courseName': self.courseName,
            'teacherName': self.teacherName,
            'courseCount': self.courseCount,
            'courseScore': self.courseScore,
        }
        return course


PythonProject/apps/Course/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.Course.models import Course
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台课程信息添加
    def primaryKeyExist(self, courseNo):  # 判断主键是否存在
        try:
            Course.objects.get(courseNo=courseNo)
            return True
        except Course.DoesNotExist:
            return False

    def get(self,request):

        # 使用模板
        return render(request, 'Course/course_frontAdd.html')

    def post(self, request):
        courseNo = request.POST.get('course.courseNo') # 判断课程编号是否存在
        if self.primaryKeyExist(courseNo):
            return JsonResponse({'success': False, 'message': '课程编号已经存在'})

        course = Course() # 新建一个课程信息对象然后获取参数
        course.courseNo = courseNo
        course.courseName = request.POST.get('course.courseName')
        course.teacherName = request.POST.get('course.teacherName')
        course.courseCount = int(request.POST.get('course.courseCount'))
        course.courseScore = float(request.POST.get('course.courseScore'))
        course.save() # 保存课程信息信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改课程信息
    def get(self, request, courseNo):
        context = {'courseNo': courseNo}
        return render(request, 'Course/course_frontModify.html', context)


class FrontListView(BaseView):  # 前台课程信息查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        courseNo = self.getStrParam(request, 'courseNo')
        courseName = self.getStrParam(request, 'courseName')
        teacherName = self.getStrParam(request, 'teacherName')
        # 然后条件组合查询过滤
        courses = Course.objects.all()
        if courseNo != '':
            courses = courses.filter(courseNo__contains=courseNo)
        if courseName != '':
            courses = courses.filter(courseName__contains=courseName)
        if teacherName != '':
            courses = courses.filter(teacherName__contains=teacherName)
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(courses, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        courses_page = self.paginator.page(self.currentPage)

        # 构造模板需要的参数
        context = {
            'courses_page': courses_page,
            'courseNo': courseNo,
            'courseName': courseName,
            'teacherName': teacherName,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'Course/course_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示课程信息详情页
    def get(self, request, courseNo):
        # 查询需要显示的课程信息对象
        course = Course.objects.get(courseNo=courseNo)
        context = {
            'course': course
        }
        # 渲染模板显示
        return render(request, 'Course/course_frontshow.html', context)


class ListAllView(View): # 前台查询所有课程信息
    def get(self,request):
        courses = Course.objects.all()
        courseList = []
        for course in courses:
            courseObj = {
                'courseNo': course.courseNo,
                'courseName': course.courseName,
            }
            courseList.append(courseObj)
        return JsonResponse(courseList, safe=False)


class UpdateView(BaseView):  # Ajax方式课程信息更新
    def get(self, request, courseNo):
        # GET方式请求查询课程信息对象并返回课程信息json格式
        course = Course.objects.get(courseNo=courseNo)
        return JsonResponse(course.getJsonObj())

    def post(self, request, courseNo):
        # POST方式提交课程信息修改信息更新到数据库
        course = Course.objects.get(courseNo=courseNo)
        course.courseName = request.POST.get('course.courseName')
        course.teacherName = request.POST.get('course.teacherName')
        course.courseCount = int(request.POST.get('course.courseCount'))
        course.courseScore = float(request.POST.get('course.courseScore'))
        course.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台课程信息添加
    def primaryKeyExist(self, courseNo):  # 判断主键是否存在
        try:
            Course.objects.get(courseNo=courseNo)
            return True
        except Course.DoesNotExist:
            return False

    def get(self,request):

        # 渲染显示模板界面
        return render(request, 'Course/course_add.html')

    def post(self, request):
        # POST方式处理图书添加业务
        courseNo = request.POST.get('course.courseNo') # 判断课程编号是否存在
        if self.primaryKeyExist(courseNo):
            return JsonResponse({'success': False, 'message': '课程编号已经存在'})

        course = Course() # 新建一个课程信息对象然后获取参数
        course.courseNo = courseNo
        course.courseName = request.POST.get('course.courseName')
        course.teacherName = request.POST.get('course.teacherName')
        course.courseCount = int(request.POST.get('course.courseCount'))
        course.courseScore = float(request.POST.get('course.courseScore'))
        course.save() # 保存课程信息信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新课程信息
    def get(self, request, courseNo):
        context = {'courseNo': courseNo}
        return render(request, 'Course/course_modify.html', context)


class ListView(BaseView):  # 后台课程信息列表
    def get(self, request):
        # 使用模板
        return render(request, 'Course/course_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        courseNo = self.getStrParam(request, 'courseNo')
        courseName = self.getStrParam(request, 'courseName')
        teacherName = self.getStrParam(request, 'teacherName')
        # 然后条件组合查询过滤
        courses = Course.objects.all()
        if courseNo != '':
            courses = courses.filter(courseNo__contains=courseNo)
        if courseName != '':
            courses = courses.filter(courseName__contains=courseName)
        if teacherName != '':
            courses = courses.filter(teacherName__contains=teacherName)
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(courses, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        courses_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        courseList = []
        for course in courses_page:
            course = course.getJsonObj()
            courseList.append(course)
        # 构造模板页面需要的参数
        course_res = {
            'rows': courseList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(course_res, json_dumps_params={'ensure_ascii':False})

class DeletesView(BaseView):  # 删除课程信息信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        courseNos = self.getStrParam(request, 'courseNos')
        courseNos = courseNos.split(',')
        count = 0
        try:
            for courseNo in courseNos:
                Course.objects.get(courseNo=courseNo).delete()
                count = count + 1
            message = '%s条记录删除成功！' % count
            success = True
        except Exception as e:
            message = '数据库外键约束删除失败！'
            success = False
        return JsonResponse({'success': success, 'message': message})


class OutToExcelView(BaseView):  # 导出课程信息信息到excel并下载
    def get(self, request):
        # 收集查询参数
        courseNo = self.getStrParam(request, 'courseNo')
        courseName = self.getStrParam(request, 'courseName')
        teacherName = self.getStrParam(request, 'teacherName')
        # 然后条件组合查询过滤
        courses = Course.objects.all()
        if courseNo != '':
            courses = courses.filter(courseNo__contains=courseNo)
        if courseName != '':
            courses = courses.filter(courseName__contains=courseName)
        if teacherName != '':
            courses = courses.filter(teacherName__contains=teacherName)
        #将查询结果集转换成列表
        courseList = []
        for course in courses:
            course = course.getJsonObj()
            courseList.append(course)
        # 利用pandas实现数据的导出功能
        pf = pd.DataFrame(courseList)
        # 设置要导入到excel的列
        columns_map = {
            'courseNo': '课程编号',
            'courseName': '课程名称',
            'teacherName': '任课教师',
            'courseCount': '总课时',
            'courseScore': '总学分',
        }
        pf = pf[columns_map.keys()]
        pf.rename(columns=columns_map, inplace=True)
        # 将空的单元格替换为空字符
        pf.fillna('', inplace=True)
        #设定文件名和导出路径
        filename = 'courses.xlsx'
        # 这个路径可以在settings中设置也可以直接手动输入
        root_path = settings.MEDIA_ROOT + '/output/'
        file_path = os.path.join(root_path, filename)
        pf.to_excel(file_path, encoding='utf-8', index=False)
        # 将生成的excel文件输出到网页下载
        file = open(file_path, 'rb')
        response = FileResponse(file)
        response['Content-Type'] = 'application/octet-stream'
        response['Content-Disposition'] = 'attachment;filename="courses.xlsx"'

PythonProject/templates/Course/course_frontquery_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>课程信息查询</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="row"> 
	<div class="col-md-3 wow fadeInLeft">
		<div class="page-header">
    		<h1>课程信息查询</h1>
		</div>
		<form name="courseQueryForm" id="courseQueryForm" action="{% url 'Course:frontList' %}" class="mar_t15" method="post">
			 {% csrf_token %}
			<div class="form-group">
				<label for="courseNo">课程编号:</label>
				<input type="text" id="courseNo" name="courseNo" value="{{ courseNo }}" class="form-control" placeholder="请输入课程编号">
			</div>
			<div class="form-group">
				<label for="courseName">课程名称:</label>
				<input type="text" id="courseName" name="courseName" value="{{ courseName }}" class="form-control" placeholder="请输入课程名称">
			</div>
			<div class="form-group">
				<label for="teacherName">任课教师:</label>
				<input type="text" id="teacherName" name="teacherName" value="{{ teacherName }}" class="form-control" placeholder="请输入任课教师">
			</div>
            <input type=hidden name=currentPage value="{{ currentPage }}" />
            <button type="submit" class="btn btn-primary">查询</button>
        </form>
	</div>

		<div class="col-md-9 wow fadeInDown" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li><a href="{% url 'Index:index' %}">首页</a></li>
			    	<li role="presentation" class="active"><a href="#courseListPanel" aria-controls="courseListPanel" role="tab" data-toggle="tab">课程信息列表</a></li>
			    	<li role="presentation" ><a href="{% url 'Course:frontAdd' %}" style="display:none;">添加课程信息</a></li>
				</ul>
			  	<!-- Tab panes -->
			  	<div class="tab-content">
				    <div role="tabpanel" class="tab-pane active" id="courseListPanel">
				    		<div class="row">
				    			<div class="col-md-12 top5">
				    				<div class="table-responsive">
				    				<table class="table table-condensed table-hover">
				    					<tr class="success bold"><td>序号</td><td>课程编号</td><td>课程名称</td><td>任课教师</td><td>总课时</td><td>总学分</td><td>操作</td></tr>
                                        {% for course in courses_page %}
 										<tr>
 											<td>{{ startIndex|add:forloop.counter }}</td>
 											<td>{{ course.courseNo }}</td>
 											<td>{{ course.courseName }}</td>
 											<td>{{ course.teacherName }}</td>
 											<td>{{ course.courseCount }}</td>
 											<td>{{ course.courseScore }}</td>
 											<td>
 												<a href="{% url 'Course:frontShow' course.courseNo  %}"><i class="fa fa-info"></i>&nbsp;查看</a>&nbsp;
 												<a href="#" onclick="courseEdit('{{ course.courseNo }}');" style="display:none;"><i class="fa fa-pencil fa-fw"></i>编辑</a>&nbsp;
 												<a href="#" onclick="courseDelete('{{ course.courseNo }}');" style="display:none;"><i class="fa fa-trash-o fa-fw"></i>删除</a>
 											</td> 
 										</tr>
 										{% endfor %}
				    				</table>
				    				</div>
				    			</div>
				    		</div>

				    		<div class="row">
					            <div class="col-md-12">
						            <nav class="pull-left">
						                <ul class="pagination">
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:-1 }},{{ totalPage }}>);" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                                            {% for page in pageList %}
                                            {% if currentPage == page %}
						                        <li class="active"><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
						                    {% else %}
                                                <li><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
                                            {% endif %}
                                            {% endfor %}
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:1 }},{{ totalPage }});"><span aria-hidden="true">&raquo;</span></a></li>
						                </ul>
						            </nav>
						            <div class="pull-right" style="line-height:75px;" >共有{{ recordNumber }}条记录，当前第{{ currentPage }}/{{ totalPage }}> 页</div>
					            </div>
				            </div> 
				    </div>
				</div>
			</div>
		</div>
		</div>
	</div> 
<div id="courseEditDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-edit"></i>&nbsp;课程信息信息编辑</h4>
      </div>
      <div class="modal-body" style="height:450px; overflow: scroll;">
      	<form class="form-horizontal" name="courseEditForm" id="courseEditForm" enctype="multipart/form-data" method="post"  class="mar_t15">
		    {% csrf_token %}
		  <div class="form-group">
			 <label for="course_courseNo_edit" class="col-md-3 text-right">课程编号:</label>
			 <div class="col-md-9"> 
			 	<input type="text" id="course_courseNo_edit" name="course.courseNo" class="form-control" placeholder="请输入课程编号" readOnly>
			 </div>
		  </div> 
		  <div class="form-group">
		  	 <label for="course_courseName_edit" class="col-md-3 text-right">课程名称:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="course_courseName_edit" name="course.courseName" class="form-control" placeholder="请输入课程名称">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="course_teacherName_edit" class="col-md-3 text-right">任课教师:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="course_teacherName_edit" name="course.teacherName" class="form-control" placeholder="请输入任课教师">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="course_courseCount_edit" class="col-md-3 text-right">总课时:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="course_courseCount_edit" name="course.courseCount" class="form-control" placeholder="请输入总课时">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="course_courseScore_edit" class="col-md-3 text-right">总学分:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="course_courseScore_edit" name="course.courseScore" class="form-control" placeholder="请输入总学分">
			 </div>
		  </div>
		</form> 
	    <style>#courseEditForm .form-group {margin-bottom:5px;}  </style>
      </div>
      <div class="modal-footer"> 
      	<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      	<button type="button" class="btn btn-primary" onclick="ajaxCourseModify();">提交</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script>
/*跳转到查询结果的某页*/
function GoToPage(currentPage,totalPage) {
    if(currentPage==0) return;
    if(currentPage>totalPage) return;
    document.courseQueryForm.currentPage.value = currentPage;
    document.courseQueryForm.submit();
}

/*可以直接跳转到某页*/
function changepage(totalPage)
{
    var pageValue=document.courseQueryForm.pageValue.value;
    if(pageValue>totalPage) {
        alert('你输入的页码超出了总页数!');
        return ;
    }
    document.courseQueryForm.currentPage.value = pageValue;
    documentcourseQueryForm.submit();
}

/*弹出修改课程信息界面并初始化数据*/
function courseEdit(courseNo) {
	$.ajax({
		url :  '/Course/update/' + courseNo,
		type : "get",
		dataType: "json",
		success : function (course, response, status) {
			if (course) {
				$("#course_courseNo_edit").val(course.courseNo);
				$("#course_courseName_edit").val(course.courseName);
				$("#course_teacherName_edit").val(course.teacherName);
				$("#course_courseCount_edit").val(course.courseCount);
				$("#course_courseScore_edit").val(course.courseScore);
				$('#courseEditDialog').modal('show');
			} else {
				alert("获取信息失败！");
			}
		}
	});
}

/*删除课程信息信息*/
function courseDelete(courseNo) {
    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	if(confirm("确认删除这个记录")) {
		$.ajax({
			type : "POST",
			url : "/Course/deletes",
			data : {
				courseNos : courseNo,
                "csrfmiddlewaretoken": csrf
			},
			success : function (obj) {
				if (obj.success) {
					alert("删除成功");
					$("#courseQueryForm").submit();
					//location.href= basePath + "Course/frontlist";
				}
				else 
					alert(obj.message);
			},
		});
	}
}

/*ajax方式提交课程信息信息表单给服务器端修改*/
function ajaxCourseModify() {
	$.ajax({
		url :   '/Course/update/' + $("#course_courseNo_edit").val(),
		type : "post",
		dataType: "json",
		data: new FormData($("#courseEditForm")[0]),
		success : function (obj, response, status) {
            if(obj.success){
                alert("信息修改成功！");
                $("#courseQueryForm").submit();
            }else{
                alert(obj.message);
            } 
		},
		processData: false,
		contentType: false,
	});
}

$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();

})
</script>
</body>
</html>


PythonProject/templates/Course/course_query_result.html
{% include 'check_logstate.html' %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static '/css/course.css' %}" />

{% csrf_token %}
<div id="course_manage"></div>
<div id="course_manage_tool" style="padding:5px;">
	<div style="margin-bottom:5px;">
		<a href="#" class="easyui-linkbutton" iconCls="icon-edit-new" plain="true" onclick="course_manage_tool.edit();">修改</a>
		<a href="#" class="easyui-linkbutton" iconCls="icon-delete-new" plain="true" onclick="course_manage_tool.remove();">删除</a>
		<a href="#" class="easyui-linkbutton" iconCls="icon-reload" plain="true"  onclick="course_manage_tool.reload();">刷新</a>
		<a href="#" class="easyui-linkbutton" iconCls="icon-redo" plain="true" onclick="course_manage_tool.redo();">取消选择</a>
		<a href="#" class="easyui-linkbutton" iconCls="icon-export" plain="true" onclick="course_manage_tool.exportExcel();">导出到excel</a>
	</div>
	<div style="padding:0 0 0 7px;color:#333;">
		<form id="courseQueryForm" method="get">
			课程编号：<input type="text" class="textbox" id="courseNo" name="courseNo" style="width:110px" />
			课程名称：<input type="text" class="textbox" id="courseName" name="courseName" style="width:110px" />
			任课教师：<input type="text" class="textbox" id="teacherName" name="teacherName" style="width:110px" />
			<a href="#" class="easyui-linkbutton" iconCls="icon-search" onclick="course_manage_tool.search();">查询</a>
		</form>	
	</div>
</div>

<div id="courseEditDiv">
	<form id="courseEditForm" enctype="multipart/form-data"  method="post">
        {% csrf_token %}
		<div>
			<span class="label">课程编号:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="course_courseNo_edit" name="course.courseNo" style="width:200px" />
			</span>
		</div>
		<div>
			<span class="label">课程名称:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="course_courseName_edit" name="course.courseName" style="width:200px" />

			</span>

		</div>
		<div>
			<span class="label">任课教师:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="course_teacherName_edit" name="course.teacherName" style="width:200px" />

			</span>

		</div>
		<div>
			<span class="label">总课时:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="course_courseCount_edit" name="course.courseCount" style="width:80px" />

			</span>

		</div>
		<div>
			<span class="label">总学分:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="course_courseScore_edit" name="course.courseScore" style="width:80px" />

			</span>

		</div>
	</form>
</div>
<script type="text/javascript" src="{% static 'js/Course/course_manage.js' %}"></script>